### ISSUE TITLE
Error when building database. Looks like a problem with the Anubis Collection

### ISSUE THREAD

**Issue by sorenba** [StiliyanKushev/csgo-tradeup-cli#16]
I am getting this error when building database. Looks like a problem with the Anubis Collection

now scraping: Winter Offensive Weapon Case
   -M4A4 | Asiimov
   -Sawed-Off | The Kraken
   -AWP | Redline
   -M4A1-S | Guardian
   -P250 | Mehndi
   -Dual Berettas | Marina
   -MP9 | Rose Iron
   -FAMAS | Pulse
   -Nova | Rising Skull
   -Five-SeveN | Kami
   -PP-Bizon | Cobalt Halftone
   -Galil AR | Sandstorm
   -M249 | Magma
now scraping: Anubis Collection
file:///C:/Users/sba/Downloads/csgo-tradeup-cli-main/utils/rarity.js:17
    rarity = rarity.toLowerCase().trim();
                    ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at rarityToNumber (file:///C:/Users/sba/Downloads/csgo-tradeup-cli-main/utils/rarity.js:17:21)
    at gunScrape (file:///C:/Users/sba/Downloads/csgo-tradeup-cli-main/scrape.js:79:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getGunsData (file:///C:/Users/sba/Downloads/csgo-tradeup-cli-main/scrape.js:68:47)
    at async updateDatabase (file:///C:/Users/sba/Downloads/csgo-tradeup-cli-main/scrape.js:277:23)
    at async buildDatabase (file:///C:/Users/sba/Downloads/csgo-tradeup-cli-main/db.js:41:5)
    at async checkEmptyDB (file:///C:/Users/sba/Downloads/csgo-tradeup-cli-main/db.js:51:9)
    at async file:///C:/Users/sba/Downloads/csgo-tradeup-cli-main/index.js:21:5

Node.js v18.16.0

**Comment by sorenba** [comment]
Maybe this is caused by ' symbol in for example P250 | Apep's Curse.

**Comment by TomiLikesToCode** [comment]
can it be fixed?

**Comment by TomiLikesToCode** [comment]
> Maybe this is caused by ' symbol in for example P250 | Apep's Curse.
> 
> 
Man-o'-war skin has "'" too

**Comment by TomiLikesToCode** [comment]
> Maybe this is caused by ' symbol in for example P250 | Apep's Curse.
> 
> 

Read my open issue for detailed problem

**Comment by ellysus** [comment]
I did some debugging, it turns out the anubis collection link has a redirect on it.

My quick and dirty fix is adding a check on the `scrape.js` file on the `gunScrape` function:

`if (url == "https://csgostash.com/collection/The+Anubis+Collection") url = "https://csgostash.com/case/378/Anubis-Collection-Package"`

This fixes it for me.

**Comment by StiliyanKushev** [comment]
Should be fixed now. Made a small change to follow redirects when scraping.
